### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by inyub** [inyub/AnotherLazyPomo#1]
- [x] Total Lazy Time needs hh:mm:ss
- [x] Total Pomo Time needs hh:mm:ss
- [x] Desktop Pin / Always on top
- [x] PomoCounter
- [x] Save/Load (only pomo counter implemented, rest is broken after loading)
- [ ] Cheat console
- [ ] Graphics
- [ ] Interpolate Timebar
- [ ] Sound
- [ ] reset current pomo function
